from enum import Enum


class UserRole(str, Enum):
    EMPLOYEE = "EMPLOYEE"
    APPROVER = "APPROVER"
    WORKFLOW_ADMIN = "WORKFLOW_ADMIN"
    AUDITOR = "AUDITOR"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class WorkflowStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class AuditEventType(str, Enum):
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    TASK_CREATED = "TASK_CREATED"
    TASK_APPROVED = "TASK_APPROVED"
    TASK_REJECTED = "TASK_REJECTED"
    WORKFLOW_ADVANCED = "WORKFLOW_ADVANCED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_REJECTED = "WORKFLOW_REJECTED"