"""create workflow audit logs table

Revision ID: 2f4af1e360f4
Revises: 0bbe9d101aa9
Create Date: 2026-07-21 13:15:04.152149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4af1e360f4'
down_revision: Union[str, Sequence[str], None] = '0bbe9d101aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_audit_logs',
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('approval_task_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.Enum('WORKFLOW_STARTED', 'TASK_CREATED', 'TASK_APPROVED', 'TASK_REJECTED', 'WORKFLOW_ADVANCED', 'WORKFLOW_COMPLETED', 'WORKFLOW_REJECTED', name='auditeventtype'), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approval_task_id'], ['approval_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_audit_logs_event_type'), 'workflow_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_workflow_audit_logs_workflow_instance_id'), 'workflow_audit_logs', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_audit_logs_workflow_instance_id'), table_name='workflow_audit_logs')
    op.drop_index(op.f('ix_workflow_audit_logs_event_type'), table_name='workflow_audit_logs')
    op.drop_table('workflow_audit_logs')
    # ### end Alembic commands ###
