"""refactor base entity

Revision ID: a952394f37f4
Revises: f17471da4968
Create Date: 2026-07-13 10:44:25.308207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a952394f37f4'
down_revision: Union[str, Sequence[str], None] = 'f17471da4968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_definitions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('workflow_definitions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_definitions', 'updated_at')
    op.drop_column('workflow_definitions', 'created_at')
    # ### end Alembic commands ###
