"""add workflow relationships

Revision ID: c450d68ce083
Revises: a952394f37f4
Create Date: 2026-07-13 12:19:18.753979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c450d68ce083'
down_revision: Union[str, Sequence[str], None] = 'a952394f37f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workflow_steps_workflow_definition_id_fkey'), 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_steps', 'workflow_definitions', ['workflow_definition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_steps', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_steps_workflow_definition_id_fkey'), 'workflow_steps', 'workflow_definitions', ['workflow_definition_id'], ['id'])
    # ### end Alembic commands ###
