"""create workflow steps table

Revision ID: f17471da4968
Revises: c99b19f737c1
Create Date: 2026-07-13 09:50:59.048228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17471da4968'
down_revision: Union[str, Sequence[str], None] = 'c99b19f737c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_definition_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('approver_role', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_workflow_name_version'), 'workflow_definitions', type_='unique')
    op.create_unique_constraint(None, 'workflow_definitions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_definitions', type_='unique')
    op.create_unique_constraint(op.f('uq_workflow_name_version'), 'workflow_definitions', ['name', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_table('workflow_steps')
    # ### end Alembic commands ###
